# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='links.Tag'),
        ),
    ]
