# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20170202_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='link',
            old_name='url',
            new_name='uri',
        ),
        migrations.AlterField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='links', to='links.Tag'),
        ),
    ]
